[build-system]
requires = [
    "setuptools",  #Use to build python library into a python package
    "wheel",   # Use to distribute packages
#    "toml"
    "bumpver"
]

[tool.bumpver]
current_version = "2024.1010-alpha"
version_pattern = "YYYY.BUILD[-TAG]"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = true
push = true

[files]
# Define the files where the version should be updated
files = ["pyproject.toml", "README.md"]

# To modify the version in files
[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'current_version = "{version}"',
]

#"setup.py" = [
#    "{version}",
#    "{pep440_version}",
#]
"README.md" = [
    "# Bash Memo {version}",
    "{pep440_version}",
]

