[build-system]
requires = [
    "setuptools",  #Use to build python library into a python package
    "wheel",   # Use to distribute packages
#    "toml"
    "bumpver"
]

[tool.bumpver]
current_version = "2024.1011-alpha"
version_pattern = "YYYY.BUILD[-TAG]"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = true
push = true

[files]
# Define the files where the version should be updated
files = ["README.md"]

# Define the regular expression pattern for the version in the README.md
# This example assumes that the version in README.md is in the format "v1.2.3"
[files."README.md"]
pattern = r"\d{4}\.\d{4}-(\w+))"  # Pattern to match version like "v1.2.3"
replacement = "{version}"       # Replacement format for the new version

# To modify the version in files
[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'current_version = "{version}"',
]

#"setup.py" = [
#    "{version}",
#    "{pep440_version}",
#]
"README.md" = [
    "# Bash Memo {version}",
    "{pep440_version}",
]



